---

- hosts: this_host
  become: yes
  connection: local
  gather_facts: yes
  tasks:
    - name: add vars depends on distr
      include_vars: "{{ ansible_os_family|lower }}.yml"
      loop:
        - "{{ ansible_os_family|lower }}.yml"
        - "{{ ansible_os_family|lower }}-packages.yml"
      tags:
        - time
        - sys
        - install_packages

    - name: install package list
      become: yes
      package:
        name: "{{ packages_sorted }}"
        state: present
      tags:
        - install_packages

    - name: include tasks for system configuration
      import_tasks: tasks/system.yml
      tags:
        - sys

    - name: include tasks for system configuration | distr
      include_tasks: tasks/{{ ansible_os_family|lower }}-tasks.yml
      tags:
        - sys

    - name: include tasks for notebook configuration
      import_tasks: tasks/notebook.yml
      when:
        - ansible_facts['virtualization_type'] != 'docker'
      tags:
        - sys

    - name: include tasks for configuring time
      import_tasks: tasks/time.yml
      when:
        - ansible_facts['virtualization_type'] != 'docker'
      tags:
        - time

  handlers:
    - name: restart journald
      service:
        name: systemd-journald
        state: restarted
      when:
        - ansible_facts['virtualization_type'] != 'docker'
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
        enabled: yes
      when:
        - ansible_facts['virtualization_type'] != 'docker'
    - name: restart_chrony
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when:
        - ansible_facts['virtualization_type'] != 'docker'
    - name: sshd_agent_user
      systemd:
        scope: user
        name: ssh-agent.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      when:
        - ansible_facts['virtualization_type'] != 'docker'

...
