---
- hosts: this_host
  connection: local
  gather_facts: true
  roles:
    - system
  # tasks:
  #   - name: dotfiles | clone
  #     git:
  #       repo: https://github.com/tenhishadow/dotfiles.git
  #       dest: "{{ ansible_user_dir }}/.dotfiles"
  #       clone: true
  #       update: true
  #   - name: install dotfiles
  #     shell:
  #       cmd: pipenv install && pipenv run configs
  #       chdir: "{{ ansible_user_dir }}/.dotfiles"

...
