---

- hosts: this_host
  become: yes
  connection: local
  gather_facts: yes
  tasks:
    - name: "vars | include for {{ ansible_os_family|lower }}"
      include_vars: "{{ item }}"
      loop:
        - "{{ ansible_os_family|lower }}.yml"
        - "{{ ansible_os_family|lower }}-packages.yml"
  roles:
    - system
  #
  #   - name: "tasks | system | {{ ansible_os_family|lower }}"
  #     include_tasks: "tasks/{{ ansible_os_family|lower }}-tasks.yml"
  #
  #   # - name: include tasks for notebook configuration
  #   #   import_tasks: tasks/notebook.yml
  #   #   when:
  #   #     - ansible_facts['virtualization_type'] != 'docker'
  #   #   tags:
  #   #     - sys
  #
  # handlers:
  #   - name: restart journald
  #     service:
  #       name: systemd-journald
  #       state: restarted
  #     when:
  #       - ansible_facts['virtualization_type'] != 'docker'
  #   - name: restart_sshd
  #     service:
  #       name: sshd
  #       state: restarted
  #       enabled: yes
  #     when:
  #       - ansible_facts['virtualization_type'] != 'docker'
  #   - name: restart_chrony
  #     service:
  #       name: chronyd
  #       state: restarted
  #       enabled: yes
  #     when:
  #       - ansible_facts['virtualization_type'] != 'docker'
  #   - name: sshd_agent_user
  #     systemd:
  #       scope: user
  #       name: ssh-agent.service
  #       state: restarted
  #       enabled: yes
  #       daemon_reload: yes
  #     when:
  #       - ansible_facts['virtualization_type'] != 'docker'

...
