---
- hosts: this_host
  connection: local
  gather_facts: true
  roles:
    - system
  tasks:
    - name: dotfiles | check already presented
      stat:
        path: "{{ ansible_user_dir }}/.dotfiles"
      register: dotfiles
      # FIXME add place a file to notify it's installed e.g. ~/.dotfiles_installed

    - name: dotfiles | clone
      git:
        repo: https://github.com/tenhishadow/dotfiles.git
        dest: "{{ ansible_user_dir }}/.dotfiles"
      when:
        - not dotfiles.stat.exists

    - name: dotfiles | install
      shell:
        cmd: pipenv install && pipenv run configs
        chdir: "{{ ansible_user_dir }}/.dotfiles"
      when:
        - not dotfiles.stat.exists

    - name: dotfiles | cronjob for update
      cron:
        name: dotfiles updates
        job: "cd {{ ansible_user_dir }}/.dotfiles && git pull"
        special_time: hourly
      ignore_errors: true # if cron not presented
...
