# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RUN_PLAYBOOK: "uv run ansible-playbook playbook_install.yml --diff {{.CLI_ARGS}}"
  DEPS_OS_ARCHLINUX: "uv git sudo"
  MITOGEN_VARS: "ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear"

tasks:
  deps-os:
    status:
      - $SHELL -c 'type -P uv'
      - $SHELL -c 'type -P git'
      - $SHELL -c 'type -P sudo'
    cmd: >-
      sudo pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
      || pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
  deps-python:
    silent: true
    deps: [deps-os]
    cmd: >-
      uv sync
      --locked
      --no-build
      --no-install-project
      --no-dev
      --managed-python
  deps-galaxy:
    silent: true
    deps: [deps-python]
    cmds:
      - "uv run ansible-galaxy install -r requirements.yml"
  deps-upgrade:
    cmds:
      - uv sync --upgrade
  lint:
    deps: [deps-python]
    cmds:
      - "uv run ansible-lint"
  clear:
    cmd: >-
      rm -rf
      .ansible
      .collections
      .task
      .venv
  default:
    deps: [deps-galaxy]
    cmd: "{{.MITOGEN_VARS}} {{.RUN_PLAYBOOK}}"
  test:
    cmd: >-
      docker run --rm -i
      -v "$(pwd):/.ans-workstation:ro"
      archlinux:latest
      bash -c 'cd .ans-workstation && ./.test/exec.sh'
      && docker system prune --volumes --force
  list:
    cmd: "uv run ansible-playbook --list-tasks playbook_install.yml"
