---

- name: "{{ansible_os_family}} - manage package src"
  become: yes
  cron:
    user: root
    name: reflector
    job: 'reflector --protocol https --latest 10 --sort rate --save /etc/pacman.d/mirrorlist >/dev/null 2>/dev/null'
    special_time: daily
  ignore_errors: true  # if cron not presented
  no_log: true         # it doesnt matter#
  when:
    - ansible_facts['virtualization_type'] != 'docker'


- name: Check if yay is in /usr/bin/yay
  stat:
    path: /usr/bin/yay
  register: yay_bin
  changed_when: false


###
- name: define temp user for installing yay
  set_fact:
    yay_install_user: "temp_usr_{{ random(seed=inventory_hostname) }}"
  when: not yay_bin.stat.exists
- name: create a user for installing yay
  user:
    name: "{{ yay_install_user }}"
  when: not yay_bin.stat.exists

###

# - name: Install dependencies
#   pacman:
#     name:
#       - base-devel
#       - git
#     state: present
#   when: not yay_bin.stat.exists

- name: Clone yay from GitHub
  become: yes
  become_user: "{{ yay_install_user }}"
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
  when: not yay_bin.stat.exists

- name: Build and install yay
  become: yes
  become_user: "{{ yay_install_user }}"
  shell: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay
  when: not yay_bin.stat.exists

...
