---

- name: blacklist camera
  become: true
  kernel_blacklist:
    name: uvcvideo
    state: present

- name: create dir for systemd user's unitfiles
  file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/"
    state: directory
  when:
    - ansible_service_mgr == "systemd"

- name: create user systemd service for ssh-agent
  become: yes
  template:
    src: "templates/ssh-agent.service.j2"
    dest: "{{ ansible_user_dir }}/.config/systemd/user/ssh-agent.service"
    backup: yes
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - sshd_agent_user

- name: start/enable in playbook
  systemd:
    scope: user
    name: ssh-agent.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: install pip packages
  pip:
    name: "{{ pip_packages }}"
    extra_args: "--local"
  tags:
    - pip

...
