---

- name: manage podman rootless
  lineinfile:
    path: "{{ item }}"
    line: "{{ ansible_user_id }}:10000:65536"
  become: yes
  loop:
    - /etc/subuid
    - /etc/subgid

- name: shut up podman
  become: yes
  copy:
    content: ''
    dest: /etc/containers/nodocker
    owner: root
    group: root
    mode: "a=r"

...
