---
version: 2.1

jobs:
  ansible_exec:
    docker:
      - image: archlinux:multilib-devel # checkov:skip=CKV_CIRCLECIPIPELINES_1 checkov:skip=CKV_CIRCLECIPIPELINES_2
    environment:
      ANSIBLE_FORCE_COLOR: "True"
    steps:
      - checkout
      - run:
          name: deps | system | install
          command: >-
            pacman -Sy --noconfirm --needed
            go-task uv git reflector
      - run:
          name: deps | system | configure mirrors
          command: >-
            reflector --protocol https --fastest 3 --threads 3
            --completion-percent 30 --score 3
            --save /etc/pacman.d/mirrorlist
      - run:
          name: exec
          command: go-task

workflows:
  ansible_exec:
    jobs:
      - ansible_exec
