---
cron_package: cronie

tzdata_package: tzdata

common_timezone: Europe/Warsaw

ntp_service: systemd-timesyncd

ntp_main:
  - 2.europe.pool.ntp.org
  - 3.europe.pool.ntp.org
  - 1.lu.pool.ntp.org
  - 2.ch.pool.ntp.org
  - 3.ch.pool.ntp.org
ntp_fallback:
  - pool.ntp.org
  - 2.arch.pool.ntp.org
  - 0.arch.pool.ntp.org
  - 3.arch.pool.ntp.org
  - 1.arch.pool.ntp.org

locales:
  - "en_US.UTF-8 UTF-8"
  - "ru_RU.UTF-8 UTF-8"
  - "pl_PL.UTF-8 UTF-8"
  - "de_DE.UTF-8 UTF-8"
...
